language: node_js
node_js:
- stable
script:
- echo "only deploy"
deploy:
  provider: firebase
  edge: true
  on:
    all_branches: true
  token:
    secure: Ak+xT60SvT6bpZ+VGqdVqwY+5IBv5sSGWBhgSQj3b4vqyu+lLg51iGZ8uffNoNcTXI8Zq7HgoX/5Q0r8FfOYo3mslaVpq3b10PsSyR4kFbwKcL0a4zksN4z3A4G5iiSC9x3yTRRBEKPiA5tD63TFKVeJioQUkgAkXy38vI+0f5ezkW8QdfGkWod8rAMsB37WILH/uK3Myw07M31/PdIyVfxlBndK0Qj3QMufcxAMM51vbr6qlz4+tdN/YPj6aKo6df1XV3jgHbaDnJ9r+mpKcGKz3jzUoS2ipqfmfEyGqmGrMD/BLs1KKO4aSeKUm5guzUZl9aWoZxT2xKzhwBKtDx8Y+CsJudpQFqLTKvwTMYsJBgRo0Msp7v6tJBcAzuQ5RgxHGxDzWWFHI5J8zCO+cUjXtpHNzT5ORZS6f4hrgEhqGC5q5C70SX9gqF4mNBASNIGpksMazVTCsy9hkJT68aPYMRxdkN9MDodrTVdPBjkfDYXRGX1ZJiMVMIly3ZpbK4ZzWk39pVywC+AafzIkR8QLwR8sFcQ9x+puOrmX1kSiQlFw7405vINw3htLEG3HlF1v0pq6M0PI4XVz1iJDx1k+2dMHJR7EbTo1rWceggXbZN5kSEvoiYPpbqHnKa9akAxneSFcI7NzeNRDxoljhMs5HTTEWMJn6lcNx05CIR8=
