language: node_js
node_js:
- stable
script:
- echo "only deploy"
deploy:
  provider: firebase
  edge: true
  on:
    all_branches: true
  token:
    secure: nCslISK55LUH9UR9miKAG2Y8dT96OeTjn2wyCliaTfDZMFiuH5I9tA//I0jinnRaCg9+3klizhb8QkCacJA7bDngUPWHi2V3/cfPh1xi/WSf2djOwgOMHS9GXGEA50ygdEcy5CSteC6bSRIfdGQJO5uinBTQeshm4kai03q4rHn2ZYGczbjVLt9MpHAW0ZThSzD8SH9qVPKZOWFJyYSVxOFKwF6JSuj/QgHhpjKvj9GywB0vuTDircHZbvcIIwNp6iQ83J1ScnRC1wHsVkQGjoF+D5FDYUavPIciAxBLIuIYNR5owEow7G0uyaFqUzOUdgf91b7Fr0Ozxd7wXhQ6A+foYtfLIC2rVXy9qC6ENtWzouj86qDK64RSRhdDVHhtNaShGjUDDsaBhMUwarUlDCgqIJaOFhLZ+3ePiHlxf098ZyqV0Uk1c5UXyOJPOy6p7P5zoGeh4uAGLfWPDgybt9wAesWbHomliRuNwlBhieXXYmO3Pq49fLkj2ByfkZvC6wlwxoMiE2uJJS2HviV0tt+oQqGtm+l4b/xdYL376GspmoGkAWoAIbM5Oublu6kQajm8vrK4BErV/gFETCpOpwyS+02QuvSH0U4OG2YLZkPLB9dW8fGcJgQfP7BOe4sCngNTUOvy2j3i5Jif/x1kawdQgfNWpeO1ck9VC3krqVI=
