language: node_js
node_js:
  - stable
script:
  - 
deploy:
  provider: firebase
  token:
    secure: P3gkls98lC7wHoiT5/V3ICA4hxmArhMYSONzuwOtg52GolahQXCDBpqgSl3X+sSQZHxcd9XznGg05xM9mz68HFbcISK1se2Scf5fda5ir6oAivoTQi3nfbaudiXeA8nevt6dU7e4/TASHd5FCrATR0Fnoa08YLw97eDAHPhWLi1QF3SzBZMQLiYKbQajhr0wtS9sJsDp6EfjGavRSuFs8UkOMsM+RNay6zWLlX47Z4XWdw1bn5NM5nQvLlg9OlQ5i+vkaAgpjeU3UuemXgKHBHIq6KQCA3Tg5L3c+WXzK5BFH7gPtefyqT8k+ycYpiPnK5ItDzdogbbeW3KSIR+oD4Z6OszsoXEtvzbVSiyAWg8HZxMeliT8DmTzsaMa3k2x+hA6EvDM/2pVB9YOQZOMs2JCXG1+y8823ZkO8i2IErKfHN4BZ2cCHOjxvGV7EJ6URbEqtgSmdrQNKJl20jmyIOOCj6kJSMj8iaSnTTFvWeqoxLvsl0DhqzWylG/Oa+n+8P3xgq8fzCQ+GdvcHaVEjjTXQbKGQ7naWsciOitK9pWEdL9vo5Aff2Z/0NjPzsh2o7np7Lro/hCKyUbOd8Uoj3Cpa3m+pYsLzw/XaEtZZuFNVaGnKhAvfKsfvhSMtzNp7I+/DrnDnTo1ZlavGkPRCI7rSRGynXKVsZLRxgsLycE=
