language: node_js
node_js:
- stable
script:
- echo "only deploy"
deploy:
  provider: firebase
  edge: true
  on:
    all_branches: true
  token:
    secure: IN4gHvu7mMRLJr81Yr7d80ADWLv7X9EWptdBBIUsC0xWPpgHlBYkOm+TCNy1E4ihnAxc8XHWajnqxx2msl1qp4vAr/idshhNTBjtkhSytA6O/pqOR4NLtvTJnr/e72d6YmXrIW1+lP8RZlDVbrP7hJ/b9rgfIIDrVbvsrR1SppMxxq5/9ceLKqgjphdzquHQQSg6uMW/FiwwoSgAh5wXOBfBfcHRH5rZ0+Brnoi81dF8kFGXDzgwC8lHK0xYItP4tY0MQbv90yMUqRd5p9TXaPqT09GITlQycNl6SkJslkrOINJYY0DUQJJXjFkBpL1auh12rflWKWzcChjiXORsxuIOtcuXD1X7oATyD2zraoDaNvMzlTwHX75i+lg9fK32zmJc8nWp5OLF8FA38XQeCKlQAm8vCdmGlf3RDnusCQjGanZMnHtcuc709XNR4JRm2rVWxOBhPDu+cmnr0+FdNhCJTpOUez7PGp7mwkoXqzpTHbJh5hBCNI1In1AypH81rrGcTn4G/UHN10+boEszNCX/k+pTJ0nWprIB795ltNePmpvfjutvT5Kfn8CnKaqPe8PnuuU6InXeU7O04iMRWnUeIEBqLteIHpep5ajbPTa5JnYVJAyYTbZVM2UvdjPP548GSfOxoymCFLdnWjxlxo+eY8za4TB2ZFDx5vuxkG8=
